=== Alexle1709/mmb-gui-electron/static/mmci-cli/models/model.schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "id",
    "internal_name",
    "path",
    "capabilities",
    "description"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "internal_name": {
      "type": "string"
    },
    "path": {
      "type": "null"
    },
    "capabilities": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "interest",
        "inflation",
        "outputgap",
        "output",
        "mp_shock",
        "fiscal_shock",
        "rules"
      ],
      "properties": {
        "interest": {
          "type": "boolean"
        },
        "inflation": {
          "type": "boolean"
        },
        "outputgap": {
          "type": "boolean"
        },
        "output": {
          "type": "boolean"
        },
        "mp_shock": {
          "type": "boolean"
        },
        "fiscal_shock": {
          "type": "boolean"
        },
        "rules":{
          "type": "array",
          "items": {
            "type": "number"
          }
        }
      }
    },
    "msr": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 33,
      "maxItems": 33
    },
    "description": {
      "type": "object",
      "required": [
        "ac_ref",
        "paper_title",
        "journal",
        "replicants_name",
        "pub_date",
        "keywords",
        "description",
        "category",
        "authors"
      ],
      "properties": {
        "ac_ref": {
          "type": "string"
        },
        "paper_title": {
          "type": "string"
        },
        "journal": {
          "type": [
            "string",
            "null"
          ]
        },
        "replicants_name": {
          "type": [
            "string",
            "null"
          ]
        },
        "pub_date": {
          "type": "string"
        },
        "keywords": {
          "type": "array"
        },
        "description": {
          "type": "string"
        },
        "category": {
          "type": "string"
        },
        "authors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== Alexle1709/mmb-gui-electron/static/mmci-cli/models/BRA_SAMBA08/BRA_SAMBA08.json
{
  "$schema": "../model.schema.json",
  "id": 49,
  "internal_name": "BRA_SAMBA08",
  "path": null,
  "capabilities": {
    "interest": true,
    "inflation": true,
    "outputgap": true,
    "output": true,
    "mp_shock": true,
    "fiscal_shock": true,
    "rules": [
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11
    ]
  },
  "msr": [
    "0.682",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "(1-0.682)*1.523",
    "0",
    "0",
    "0",
    "(1-0.682)*0.839*4",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "1",
    "0.25"
  ],
  "description": {
    "ac_ref": "Gouvea et al. (2008)",
    "paper_title": "Samba: Stochastic analytical model with a bayesian approach",
    "journal": "unpublished",
    "replicants_name": "Ali Mazyaki",
    "pub_date": "2008",
    "keywords": [],
    "description": "Model of the Brazilian economy",
    "category": "Estimated other-country model",
    "authors": [
      "Gouvea, Solange",
      "Minella, Andr√©",
      "Santos, Rafael",
      "Souza-Sobrinho, Nelson"
    ]
  }
}
